# this module contains classes and functions needed to
# convert the ascii codes from a ebcdic comp-3 fields stored on a Unix File System

class asciiEbcdicConversion:

    ascii_packed_map = dict()

    def __init__(self):
        
        # this dictionary maps the ascii codes for the non-printable characters
        # back to the equivalent number pair, assuming the source file came from ebcdic platform
        
        self.ascii_packed_map =        {'0':'00',
                                        '1':'01',
                                        '2':'02',
                                        '3':'03',
                                        '4':'37',
                                        '5':'-2',
                                        '8':'16',
                                        '9':'05',
                                        '12':'+0',
                                        '13':'-0',
                                        '16':'10',
                                        '17':'11',
                                        '18':'12',
                                        '19':'13',
                                        '20':'+3',
                                        '21':'-3',
                                        '22':'32',
                                        '23':'26',
                                        '24':'18',
                                        '25':'19',
                                        '27':'27',
                                        '28':'+1',
                                        '29':'-1',
                                        '32':'40',
                                        '37':'+6',
                                        '38':'50',
                                        '39':'-7',
                                        '40':'-4',
                                        '41':'-5',
                                        '42':'+5',
                                        '45':'60',
                                        '47':'61',
                                        '60':'+4',
                                        '64':'+7',
                                        '95':'-6',
                                        '96':'79',
                                        '97':'81',
                                        '98':'82',
                                        '99':'83',
                                        '100':'84',
                                        '101':'85',
                                        '102':'86',
                                        '103':'87',
                                        '104':'88',
                                        '105':'89',
                                        '106':'91',
                                        '107':'92',
                                        '108':'93',
                                        '109':'94',
                                        '110':'95',
                                        '111':'96',
                                        '112':'97',
                                        '113':'98',
                                        '114':'99',
                                        '127':'07',
                                        '128':'04',
                                        '129':'06',
                                        '130':'08',
                                        '131':'09',
                                        '133':'14',
                                        '134':'15',
                                        '135':'17',
                                        '138':'20',
                                        '139':'21',
                                        '140':'22',
                                        '141':'23',
                                        '142':'24',
                                        '143':'28',
                                        '144':'29',
                                        '147':'+2',
                                        '148':'30',
                                        '149':'31',
                                        '151':'33',
                                        '152':'34',
                                        '153':'35',
                                        '154':'36',
                                        '155':'-9',
                                        '156':'38',
                                        '157':'39',
                                        '173':'41',
                                        '176':'90',
                                        '192':'64',
                                        '193':'65',
                                        '194':'62',
                                        '195':'66',
                                        '196':'63',
                                        '197':'67',
                                        '199':'68',
                                        '200':'74',
                                        '201':'71',
                                        '202':'72',
                                        '203':'73',
                                        '204':'78',
                                        '205':'75',
                                        '206':'76',
                                        '207':'77',
                                        '209':'69',
                                        '216':'80',
                                        '223':'59',
                                        '224':'44',
                                        '225':'45',
                                        '226':'42',
                                        '227':'46',
                                        '228':'43',
                                        '229':'47',
                                        '230':'+9',
                                        '231':'48',
                                        '232':'54',
                                        '233':'51',
                                        '234':'52',
                                        '235':'53',
                                        '236':'58',
                                        '237':'55',
                                        '238':'56',
                                        '239':'57',
                                        '240':'+8',
                                        '241':'49',
                                        '248':'70',
                                        '253':'-8'
                                        }

    def getNumberPair(self,nonPrintAsciiChar):

        # this accepts the non printable Ascii character
        # extracts the ascii code of that character
        # translates that ascii code to a number pair as if coming from ebcdic platform

        asciiCode = ord(nonPrintAsciiChar)

        return(self.ascii_packed_map[str(asciiCode)])
        #end of function
